export const productosData = [
  { name: "ABC X 5 KG 2012", cat: "Extintores", desc: "", img: "" },
  { name: "ABC X 5 KG 2012", cat: "Extintores", desc: "", img: "" },
  { name: "AGUA X 10LTS 2010", cat: "Extintores", desc: "", img: "" },
  { name: "BALDE", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "BALDE DE ARENA CONTRA INCENDIO DE METAL", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "BALIZA DOBLE", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "BALIZA ROTATIVA OVAL 12W", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "BALIZA SIMPLE CON ESTUCHE", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "BALIZA SIMPLE HOMOLOGADA", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "BANDERA PELIGRO ROJA Y BLANCA 500 X 700 MM", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "BANDERA ROJA  Y BLANCA SEÑALIZACION PRECAUCION 50 X 70 CM", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "BC X 3,5KG 2011", cat: "Extintores", desc: "", img: "" },
  { name: "BC X 5KG 2012/2013", cat: "Extintores", desc: "", img: "" },
  { name: "BOLSA MORGUERA", cat: "Otros", desc: "", img: "" },
  { name: "BOLSAS MORTUORIAS 10 UNIDADES", cat: "Otros", desc: "", img: "" },
  { name: "BOLSO DE KIT", cat: "Otros", desc: "", img: "" },
  { name: "BOQUILLA DE BC", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "BOTIQUIEN MINI", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN  VIAJERO GRANDE", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN 11 ELEMENTOS VC", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN 43 ELEMENTOS COLGANTE TL", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN MADERA GRANDE MB 32X24CM", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN MADERA MG ECO", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN MADERA MX", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN P 10 ECO", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN P A ECO", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN P B", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN PRIMEROS AUXILIOS MODELO P10  ECONOMICO", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN PRIMEROS AUXILIOS PA MINI ECONOMICO", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN ROJO O BLANCO 24 ELEMENTOS", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN T A", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN T E ( ROJO Y BLANCO)", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN T J", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN T K", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN TB (BICICLETA)", cat: "Botiquines", desc: "", img: "" },
  { name: "BOTIQUIN TF", cat: "Botiquines", desc: "", img: "" },
  { name: "CABLE DE REMOLQUE", cat: "Izaje y Remolque", desc: "", img: "" },
  { name: "CADENA PASTICA VIAL MODELO 0.6 MM-NA- x50 MTS", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CADENA PLASTICA NARANJA 0.8 MM X 50 MTS", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CADENA PLASTICA VARIOS COLORES POR MT", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CADENA PLASTICA VIAL  06 MM -NE-AM-50 MTS", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CADENA PLASTIVCA VIAL 6MM-RO-BL-50MTS", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CAJA GUANTES NITRILO", cat: "Guantes de Seguridad", desc: "", img: "" },
  { name: "CALCO CARGAS PELIGROSAS 35 X 22 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CALCO ENTRADA 7 X 24", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CALCO MATERIAL ABSORBENTE 7 X 14 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CALCO PELIGRO INFLAMABLE 25 X 25 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CALCO RIESGO ELECTRICO", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CALCOS PROHIBIDO ESTACIONAR", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CALCOS PROHIBIDO FUMAR", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CALCOS USE ESCALERA", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CALCOS VELOCIDAD", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CALCOS VELOCIDAD MAXIMA 90", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL  ESCALERA FUERA DE SERVICIO 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL 22 X 26", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ALARMA INCENDIO 30 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ALRMA EN CASO DE INCENDIO ROMPA EL VIDRIO 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL APILE CORRECTAMENTE", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL APILE CORRECTAMENTE 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL APILE CORRECTAMENTE 40 X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ASCENSOR 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ASCENSOR DERECHA FOTOLUMINISCENCE 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ASCENSOR IZQUIERDA FOTOLUMINISCENCE 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ATENCION 45 X 40CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ATENCION AL TRABAJAR EN ALTA TENSION 30 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ATENCION LEVANTE CARGAS C/CUIDADO 22 X 28CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ATENCION VEHICULOS INDUSTRIALES 40X45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL AUTONOMO SALIDA", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL BAÑO CABALLERO", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL BAÑO DAMA", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL BAÑOS 14 X 30 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL CABALLETE PISO MOJADO", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL CALZADO DE SEGURIDAD 40 X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL CASCO DE SEGURIDAD 40 X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL CHOQUE ELECTRICO 40X45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL CIRCULE CON PRECAUCION 40X45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL COLOQUE LA PUESTA A TIERRA 30 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL DE ENTRADA O SALIDA CON FLECHAS", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL DIRECCION OBLIGATORIA IZQUIERDA 40X45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL DUCHA DE EMERGENCIA 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL EN CASO DE INCENDIO NO USE ASCENSOR", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ENTRADA 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ENTRADA 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ENTRADA 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ENTRADA DERECHA 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ENTRADA FOTOLUMINISCENSE 14 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ENTRADA IZQUIERDA 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ESCALERA ABAJO DERECHA 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ESCALERA ABAJO IZQUIERDA 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ESCALERA ARRIBA DERECHA 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ESCALERA ARRIBA IZQUIERDA 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ESCALERA DE EMERGENCIA 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ESCALERA DERECHA 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ESCALERA FOTOLUMINISCENSE 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ESCALERA FOTOLUMINISCENSE 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL EVACUACION INCENDIO 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL FLECHAS 14 X 14 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL FLECHAS FOTOLUMINISENCE 14 X 14 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL GUANTES DE SEGURIDAD 40 X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL GUARDARROPA 14 X 30 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL GUIA DE EVACUACIÓN 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL HOMBRES TRABAJANDO 45X 40CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL INCENDIO 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL INFLAMABLE", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL INFLAMABLE", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL LAVA OJOS DE EMERGENCIA 14X28CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL LUZ DE EMREGENCIA 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL MANTENGA LIMPIO Y ORDENADO 30 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL MASCARA DE SOLDAR 40 X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL MATAFUEGOS 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL MATAFUEGOS 30 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL MATAFUEGOS DOBLE FAZ 21 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL MATFUEGOS DOBLE FAZ 30 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL MAXIMA 15", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL NICHO HIDRANTE 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL NICHOS HIDRANTES DOBLE FAZ 21 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL NO TRANSPORTAR PERSONAS 45 CM X 40CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL NO UTILIZAR CELULAR EN ESTE AREA 20 X 27CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL OBLIGACION A PASO DE HOMBRE 40X45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL OBLIGACION ROPA DE TRABAJO 40X45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL OBLIGACION USAR CALZADO 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL OBLIGACION USAR COFIA 45 X 40CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL OBLIGACION USAR GUANTES 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL OBLIGACION USAR MASCARA FACIAL 40X45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL OBLIGACION USAR PROTECTORES AUDITIVOS 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL OBLIGACION USAR PROTECTORES OCULARES 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL OBLIGACION USO CALZADO DE SEGURIDAD 22 X 28CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL OBLIGACION USO PROTECCION OCULAR 22 X 28CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL OBLIGATORIO USAR GUANTES DE SEGURIDAD 23 X 27 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PELIGRO DESCARGA DE COMBUSTIBLE 30 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PELIGRO INCENDIO 45X 40CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PELIGRO OBRA EN CONSTRUCCION 45X 40CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PELIGRO RESPETE LAS NORMAS DE SEGURIDAD 30 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PLASTICO 22 X 28", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PRIMEROS AUXILIOS 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO EL PASO A PERS AJENA A LA EMPR 40 X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO EL PASO A TODA PERSONA AJENA AL SECTOR 40X45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO ENTRADA A TODA PERSONA AJENA A LA OBRA 40X45CM CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO ESTACIONAR", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO ESTACIONAR 30 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO ESTACIONAR 40 X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO ESTACIONAR GRUA REMUEVE 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO FUMAR", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO FUMAR 30 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO PASAR", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO PASAR 40 X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO PERSONAS AJENAS AL SECTOR", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROHIBIDO TRANSPORTAR PERSONAS 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROTECCION LUMBAR 40 X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PROTECCION OCULAR 40 X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PUERTA DE ESCAPE 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PUNTO DE REUNION 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PVC 40 X 45 CM ESPECIALES", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL PVC 40X 45 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL REFLECTIVO SUSTSNCIAS PELIGROSAS 25 X 25 MM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL RIESGO CHOQUE ELECTRICO 22 X 28 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL RIESGO CHOQUE ELECTRICO 45 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL ROPA DE TRABAJO 40 X 45 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALA DE MEDIDORES 22 X 28CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALA DE MEDIDORES 40X45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA  DERECHA 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA ABAJO IZQUIERDA 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA ARRIBA 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA D EMERGENCIA 30X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA DE EMERGENCIA  DERECHA14X41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA DE EMERGENCIA 14X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA DE EMERGENCIA A LA IZQ 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA DER 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA DERECHA 14X41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA EMERGENCIA SINOLUX", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA FOTO LUMINISCENTE DERECHA 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA FOTOLUMINISCENSE 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA IZQ 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA IZQUIERDA 14 X 41 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA LATERAL DERECHO ARRIBA 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA LATERAL IZQUIERDO ARRIBA 14 X 41CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SALIDA SEÑALIZADOR GAMASONIC 5LED", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SEÑALIZADOR GAMASONIC GX- 5 LED", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SEÑALIZADOR PISO MOJADO TIPO CARPA", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SEGURIDAD CIRCULE CON PRECAUCION 45 X 40CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SIN SALIDA ARRIBA", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL SUSTANCIAS PELIGROSAS NARANJA Y NEGRO 22 X 35 MM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL TOMESE DEL PASAMANOS ESCALERA 30 X 30 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL USAR PROTECTORES AUDITIVOS 40 X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL VEHICULO PASO DE HOMBRE 40 X 45CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL VEHICULOS INDUSTRIALES 45X 40CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL VELOCIDAD 90", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "CARTEL VELOCIDAD MAXIMA 10KM 30 X 40 CM", cat: "Carteles y Señalización", desc: "", img: "" },
  { name: "Certificado profesional de seguridad antisiniestral", cat: "Otros", desc: "", img: "" },
  { name: "CHALECO REFRACTARIO", cat: "Elementos de Protección Personal (EPP)", desc: "", img: "" },
  { name: "CHAPA BALIZA  TRES COLORES ABC", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "CHAPA BALIZA ECO A", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "CHAPA BALIZA ECO AB", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "CHAPA BALIZA ECO ABC", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "CHAPA BALIZA ECO BC", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "CHAPA BALIZA ECO BC", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "CHAPA BALIZA TRES COLORES A", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "CHAPA BALIZA TRES COLORES A", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "CHAPA BALIZA TRES COLORES AB", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "CHAPA BALIZA TRES COLORES BC", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "CINTA AMARILLA DEMARCATIVA PISO 18 MTS", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CINTA AMARILLA Y NEGRA POR METRO", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CINTA ANTIDESLIZANTE AUTOADHESIVA NEGRA Y AMARILLA 48 MM X 33 MTS", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CINTA ANTIDESLIZANTE FOTOLUMINISCENTE 5  MM POR 18 MTS", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CINTA ANTIDESLIZANTE NEGRA  ESCALERA 2,5 MM  X 18 M", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CINTA ANTIDESLIZANTE REFLECTIVA POR METRO", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CINTA NEGRA Y AMARILLA AUTOADHESIVA X 18MTS  DE 2,5 ANCHO", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CINTA PELIGRO", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CINTA REFLECTIVA BLANCA X 45 MTS 3MM", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CINTA REFLECTIVA BLANCAY AMARILLA POR MT", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CINTA REFLECTIVA CEBRADA ROJA Y BLANCA", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CINTA REFLECTIVA ROJA X 45 MTS 3 MM", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CINTA REFLECTIVA ROJA,75  POR MT", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CONO  VIAL NARANJA SEMI FLEXIBLE BASE RIGIDA 75 CMS", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CONO PP SPORT 20 CM", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CONO RIGIDO 30 CMS SEÑALIZACION VUIAL DEPORTIVO BASE REDONDA", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CONO VIAL NARANJA SEMI FLEXIBLE BASE RIGIDA 50 CMS", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CORTINA REFLECTIVA", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "CRIQUE CARRITO GATO HIDRAULICO 2 TONELADAS REFORZADO", cat: "Izaje y Remolque", desc: "", img: "" },
  { name: "CRIQUE TIJERA 1 TONELADA", cat: "Izaje y Remolque", desc: "", img: "" },
  { name: "CUARTA REMOLQUE", cat: "Izaje y Remolque", desc: "", img: "" },
  { name: "DETECTOR DE GAS SIN BATERIA", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "DETECTOR DE GAS SIN BATERIA", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "DETECTOR DE HUMO", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "DETECTOR DE HUMO CON BATERIA", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "DETECTOR DE HUMO SIN BATERIA", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "DETECTOR DE HUMO SIN BATERIA GENERAL PURPOSE", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "ESDLINGA REMOLQUE 2.5MTS", cat: "Izaje y Remolque", desc: "", img: "" },
  { name: "ESLINGA CRIQUET 5TN 10 MTS", cat: "Izaje y Remolque", desc: "", img: "" },
  { name: "ESLINGA REMOLQUE 5 MTS 3 TONELADAS", cat: "Izaje y Remolque", desc: "", img: "" },
  { name: "EXTINTOR A BASE DE DIOXIDO DE CARBONO 3,5 USADO", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE ABC 25 KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE ABC HCFC 2,5 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE ABC HCFC 5 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE AFFF 10 LTS 2017", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE AFFF 10 LTS 2019", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE AFFF 25 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE AFFF 50 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE AGUA 10 LTS 2024", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE AGUA 100 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE AGUA 25 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE AGUA 50 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE ACETATO DE  POTASIO K POR 6 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE AFFF POR 50 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE AFFF POR 70 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE AGUA  10 LTS USADO", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE CO2 POR 5 KS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE DIOXIDO DE CARBONO 10KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE HCFC DE 2,5 LTS  USADO 2016", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE HCFC NO MAGNETICO 5 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE HCFC POR 10 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE POLVO QUIMICO POR  100 KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE POLVO QUIMICO POR 100 KS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE POLVO QUIMICO POR 5 KS USADO", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DE POLVO QUIMICO POR 50 KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DIOXIDO DE CARBONO  3,5 KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DIOXIDO DE CARBONO  7 KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DIOXIDO DE CARBONO 10KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DIOXIDO DE CARBONO 2 KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DIOXIDO DE CARBONO 20 KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DIOXIDO DE CARBONO 5 KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE DIOXIDO DE CARBONO X 10KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE K 10 LTS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE POLVO QUIMICO 1 KG BALON", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE POLVO QUIMICO 10 KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE POLVO QUIMICO 1KG LARGO", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE POLVO QUIMICO 2,5 KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE POLVO QUIMICO 2,5 KG NUEVO 2022", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL A BASE POLVO QUIMICO 5 KG", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTOR MANUAL ABC POR 50 KS", cat: "Extintores", desc: "", img: "" },
  { name: "EXTINTORES USADOS", cat: "Extintores", desc: "", img: "" },
  { name: "FAJA LUMBAR DE TRABAJO", cat: "Elementos de Protección Personal (EPP)", desc: "", img: "" },
  { name: "FUNDA PARA EXTINTOR LARGO", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "FUNDAS PARA EXTINTOR BALON", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "FUNDAS PARA EXTINTORES 50 KS", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "GABINETE CON  VIDRIO PARA ABC POR 5 KS", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "GABINETE HIDRANTE CON VIDRIO", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "GABINETE METALICO SIN VIDRIO P/MANGUERA DE INCENDIO DE 2\" Y 2\" 1/2 ESTANDAR", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "GABINETE PARA ABC DE 5 KS SIN VIDRIO", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "GABINETE PARA CO2 DE 3,5 KG", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "GABINETE SIN VIDRIO PARA ABC POR 10 KS", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "GANCHOS PARA EXTINTORES", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "GANCHOS PARA EXTINTORES", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "GANCHOS PARA EXTINTORES", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "GANCHOS PARA EXTINTORES", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "GUANTES ACRILONITRILO POR PAR", cat: "Guantes de Seguridad", desc: "", img: "" },
  { name: "GUANTES DE ACRILONITRILO PUÑO RECTO", cat: "Guantes de Seguridad", desc: "", img: "" },
  { name: "GUANTES DE NITRILO DESCARTABLES RESISTENTES CAJA POR 100 UN", cat: "Guantes de Seguridad", desc: "", img: "" },
  { name: "GUANTES MOTEADOS", cat: "Guantes de Seguridad", desc: "", img: "" },
  { name: "GUANTES MOTEADOS POR PAR", cat: "Guantes de Seguridad", desc: "", img: "" },
  { name: "GUANTES SOLADOR", cat: "Guantes de Seguridad", desc: "", img: "" },
  { name: "ION DISEÑO INDUSTRIAL  SH", cat: "Otros", desc: "", img: "" },
  { name: "KIT VIAJERO", cat: "Otros", desc: "", img: "" },
  { name: "LANZA CHORRO BCE DE 1 3/4\" X 20 MTS", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "LANZA DE BRONCE CON BOQUILLA (CHORRO PLRNO) 44,5 MM 1 3/4\"", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "LANZAS 1 3/4 15 MTS CON SELLO", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "LLAVE AJUSTA UNIONES UNIVERSAL CON PINTURA", cat: "Izaje y Remolque", desc: "", img: "" },
  { name: "LLAVE CRUZ", cat: "Izaje y Remolque", desc: "", img: "" },
  { name: "LLAVE CRUZ PINTADA UNIVERSAL CON 4 BOCAS 17, 19, 21 Y 23", cat: "Izaje y Remolque", desc: "", img: "" },
  { name: "LUZ DE EMERGENCIA 2020 LITIO COMPACTO 60LED ATOMLUX", cat: "Luces de Emergencia", desc: "", img: "" },
  { name: "LUZ DE EMERGENCIA 30 LED ATOMLUX", cat: "Luces de Emergencia", desc: "", img: "" },
  { name: "LUZ DE EMERGENCIA 30 LED PRACTILED", cat: "Luces de Emergencia", desc: "", img: "" },
  { name: "LUZ DE EMERGENCIA 60 LED ATOMLUX", cat: "Luces de Emergencia", desc: "", img: "" },
  { name: "LUZ DE EMERGENCIA 60 LED GAMASONIC", cat: "Luces de Emergencia", desc: "", img: "" },
  { name: "LUZ DE EMERGENCIA 60 LED PRACTILED", cat: "Luces de Emergencia", desc: "", img: "" },
  { name: "LUZ DE EMERGENCIA 90 LED GAMASONIC", cat: "Luces de Emergencia", desc: "", img: "" },
  { name: "LUZ DE EMERGENCIA SICA 60LED 5HS DE AUTONOMIA", cat: "Luces de Emergencia", desc: "", img: "" },
  { name: "LUZ LED 2W PRACTILED", cat: "Luces de Emergencia", desc: "", img: "" },
  { name: "LUZ LED 30 LEDS ATOMLUX", cat: "Luces de Emergencia", desc: "", img: "" },
  { name: "LUZ LED 60W PRACTILED", cat: "Luces de Emergencia", desc: "", img: "" },
  { name: "LUZ LED EMERGENCIA 30 LED PRACTILED", cat: "Luces de Emergencia", desc: "", img: "" },
  { name: "MANGUERA 44.5 15 MTS", cat: "Mangueras", desc: "", img: "" },
  { name: "MANGUERA CHANCHAS X 50", cat: "Mangueras", desc: "", img: "" },
  { name: "MANGUERA DE 1 3/4 15 MTS CON SELLO", cat: "Mangueras", desc: "", img: "" },
  { name: "MANGUERA DE 1 3/4 25 MTS CON SELLO", cat: "Mangueras", desc: "", img: "" },
  { name: "MANGUERA DE INCENDIO 2 PULGADAS 25 MTS SELLO IRAM", cat: "Mangueras", desc: "", img: "" },
  { name: "MANGUERA DE INCENDION 13/4\" X 20 MTS CON UNION HOMOLOGADA", cat: "Mangueras", desc: "", img: "" },
  { name: "MANGUERA EXTINTOR", cat: "Mangueras", desc: "", img: "" },
  { name: "MANGUERA EXTINTOR AFFF 50 LTS", cat: "Mangueras", desc: "", img: "" },
  { name: "MANGUERA PARA CO2 1.5 MTS", cat: "Mangueras", desc: "", img: "" },
  { name: "MANGUERAS", cat: "Mangueras", desc: "", img: "" },
  { name: "MANGUERAS PARA EXTINTOR ABC POR 50 LTS", cat: "Mangueras", desc: "", img: "" },
  { name: "MANIJA EXTINTOR", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "MANIJAS EXTINTORES MAS DE 2,5 K", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "MANO DE OBRA", cat: "Otros", desc: "", img: "" },
  { name: "MANOMETRO", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "MANOMETRO", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "MANTA APAGA LLAMAS", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "MANTA MORTUORIA", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "MARBETES DE 10KG", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "MARBETES DE 1KG", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "MARBETES DE 5KG", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "MARTILLO CON TRINCHETA PARA OMNIBUS", cat: "Otros", desc: "", img: "" },
  { name: "NICHO HIDRANTE", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "OBLEAS", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "ORRIGN BOLSA", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "ORRING", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "PEDESTAL MATAFUEGO", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "PRECINTO A PARTIR 2,5 KS", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "PRECINTO CON LOGO", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "PRECINTOS AZULES", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "PRECINTOS NEGROS", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "PROTECTOR AUDITIVO TIPO TAPON", cat: "Protectores Auditivos", desc: "", img: "" },
  { name: "PROTECTOR LUMBAR", cat: "Elementos de Protección Personal (EPP)", desc: "", img: "" },
  { name: "REDUCCIONES 2 1/2 A 1 3/4 BRONCE", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "REPELENTE MOSQUITOS INFLUENCIA", cat: "Elementos de Protección Personal (EPP)", desc: "", img: "" },
  { name: "REPELENTES", cat: "Elementos de Protección Personal (EPP)", desc: "", img: "" },
  { name: "ROBINETE", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "ROLLO DE VIRULANA BOLSA X 10", cat: "Otros", desc: "", img: "" },
  { name: "SEGUROS EXTINTORES", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "SELLOS IRAM", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "SEPARADORES DE FILA", cat: "Vial y Tránsito", desc: "", img: "" },
  { name: "SOPORTE ABC POR  5 KS", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "SOPORTE ABC POR 10 KS", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "SOPORTE ABROJO 1KG", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "SOPORTE DE ABC 2.5K 5K", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "SOPORTE EXTINTOR ABC POR 2,5 KS", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "SOPORTE METALICO BALON", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "SOPORTE METALICO LARGO", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "SOPORTE METALICO PARA MATAFUEGO DE 1 K", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "SUJECION DE CARGA CINTA 50MM 10MT", cat: "Izaje y Remolque", desc: "", img: "" },
  { name: "SUJECION DE CARGA CINTA 50MM 36MT", cat: "Izaje y Remolque", desc: "", img: "" },
  { name: "SUJETA MANGUERAS", cat: "Otros", desc: "", img: "" },
  { name: "SUNCHOS PARA EXTINTOR", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "TANQUE PLASTICO IBC PARA 1000 LTS (1° USO)", cat: "Otros", desc: "", img: "" },
  { name: "TOBERAS", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "TOBERAS GRANDE", cat: "Accesorios para Extintores", desc: "", img: "" },
  { name: "VALVULA  DE 1/2", cat: "Red contra Incendios", desc: "", img: "" },
  { name: "VASTAGO PARA EXTINTOR", cat: "Accesorios para Extintores", desc: "", img: "" },
];

export const categories = [
  "Extintores",
  "Mangueras",
  "Carteles y Señalización",
  "Luces de Emergencia",
  "Botiquines",
  "Elementos de Protección Personal (EPP)",
  "Cascos de Seguridad",
  "Protectores Auditivos",
  "Protección Ocular y Facial",
  "Protección Respiratoria",
  "Guantes de Seguridad",
  "Accesorios para Extintores",
  "Repuestos para Extintores",
  "Red contra Incendios",
  "Vial y Tránsito",
  "Izaje y Remolque",
  "Otros",
];

export const categoryGroups = {
  "Elementos de Protección Personal (EPP)": [
    "Cascos de Seguridad",
    "Protectores Auditivos",
    "Protección Ocular y Facial",
    "Protección Respiratoria",
    "Guantes de Seguridad",
  ],
};

export const defaultConfig = {
  categories,
  groups: categoryGroups,
  colors: {},
};
